### PR TITLE
optimize Trigrams

### PR DESCRIPTION
**Pull request by Merovius**
Nerd-snipe successful :) This isn't really production-ready or anything, it's just how far I got during your talk. I'd be happy to try to do more, but I think it would be beneficial to have the full context and I couldn't find the actual server code.

Some low-hanging fruit. With more context, there could probably be more savings (like replacing the []string return with an iterator-type).

On my machine, this speeds up the simple benchmark from ~200 μs/op to ~80 μs/op.

### CODE REVIEW

**Comment by Merovius** [comment]
Okay, made it a bit faster still :)

**Comment by boyter** [comment]
Sweet. Im going to do a benchmark of all of the PR's against my best effort and turn it into a blog post, and then merge the winner.

**Comment by boyter** [comment]
Have noticed this crashes on some inputs. I need to get this down to a single case to identify the fix.

```
$ indexer --trigram=merovius
panic: runtime error: slice bounds out of range [:10] with length 8

goroutine 1 [running]:
main.TrigramsMerovius({0x14000192480, 0x8})
	/Users/boyter/Documents/projects/indexer/caisson.go:151 +0x260
main.Tokenize({0x14000192240?, 0x14000192000?})
	/Users/boyter/Documents/projects/indexer/caisson.go:79 +0x1a4
main.main.func1({0x14000191940, 0x1c}, {0x10047e140?, 0x1400047eea0?}, {0x0?, 0x0?})
	/Users/boyter/Documents/projects/indexer/main.go:50 +0xa8
path/filepath.walk({0x14000191940, 0x1c}, {0x10047e140, 0x1400047eea0}, 0x10047d578)
	/usr/local/go/src/path/filepath/path.go:484 +0xc8
path/filepath.walk({0x14000563c50, 0xc}, {0x10047e140, 0x1400047ea90}, 0x10047d578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.walk({0x1400006d78c, 0x4}, {0x10047e140, 0x14000296000}, 0x10047d578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.walk({0x10043cc60, 0x1}, {0x10047e140, 0x140000a8680}, 0x10047d578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.Walk({0x10043cc60, 0x1}, 0x10047d578)
	/usr/local/go/src/path/filepath/path.go:579 +0x6c
main.main()
	/Users/boyter/Documents/projects/indexer/main.go:25 +0x114
```

**Comment by boyter** [comment]
I have pushed some code to master which allows you to replicate it. Seems to happen on most repositories I have tried. If you feel like trying, pull master build and then try it over the redis source code for example.

```
# boyter @ bens-air in ~/Documents/projects/redis on git:unstable o [17:15:44] 
$ git --no-pager log --decorate=short --pretty=oneline -n1

88e83e517bf2b5271c4df435ec9daf4a6c132230 (HEAD -> unstable, origin/unstable, origin/HEAD) Add DEBUG_ASSERTIONS option to custom assert (#12667)

# boyter @ bens-air in ~/Documents/projects/redis on git:unstable o [17:15:46] 
$ indexer --trigram=merovius                              
panic: runtime error: slice bounds out of range [:10] with length 8

goroutine 1 [running]:
main.TrigramsMerovius({0x140003a6480, 0x8})
	/Users/boyter/Documents/projects/indexer/caisson.go:151 +0x260
main.Tokenize({0x140003a6240?, 0x140003a6000?})
	/Users/boyter/Documents/projects/indexer/caisson.go:79 +0x1a4
main.main.func1({0x140003a2460, 0x1c}, {0x100312140?, 0x14000423a00?}, {0x0?, 0x0?})
	/Users/boyter/Documents/projects/indexer/main.go:50 +0xa8
path/filepath.walk({0x140003a2460, 0x1c}, {0x100312140, 0x14000423a00}, 0x100311578)
	/usr/local/go/src/path/filepath/path.go:484 +0xc8
path/filepath.walk({0x1400017d350, 0xc}, {0x100312140, 0x140002eb1e0}, 0x100311578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.walk({0x1400016da1c, 0x4}, {0x100312140, 0x14000422270}, 0x100311578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.walk({0x1002d0c60, 0x1}, {0x100312140, 0x140001085b0}, 0x100311578)
	/usr/local/go/src/path/filepath/path.go:508 +0x1d4
path/filepath.Walk({0x1002d0c60, 0x1}, 0x100311578)
	/usr/local/go/src/path/filepath/path.go:579 +0x6c
main.main()
	/Users/boyter/Documents/projects/indexer/main.go:25 +0x114

```

**Comment by Merovius** [comment]
Don't care enough TBQH. With open source, I'd investigate and try to fix, but as is, this was just a fun drive-by thing. But it seems you have enough other contributions for this anyways :)

**Pull request closed without merging**
